"""agregar budget_alerts

Revision ID: f2ebdae7fcea
Revises: 5e6444609a53
Create Date: 2026-08-31 19:44:15.049669-03:00

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'f2ebdae7fcea'
down_revision: str | None = '5e6444609a53'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_alerts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('BUDGET_EXCEEDED', 'BUDGET_AT_RISK', 'UNBUDGETED_SPENDING', name='alert_type'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'READ', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('projected_percentage', sa.Numeric(precision=7, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', 'period_month', 'type', name='uq_budget_alerts_user_category_period_type'),
    mysql_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_budget_alerts_user_status', 'budget_alerts', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_budget_alerts_user_status', table_name='budget_alerts')
    op.drop_table('budget_alerts')
    # ### end Alembic commands ###
